services:
  web:
    image: nginx:stable-bullseye
    container_name: web
    ports:
      - "80:80"
    volumes:
      - ./src/node/web:/usr/share/nginx/html
      - ./work:/work
    working_dir: /usr/share/nginx/html
    tty: true # 開発時のみ有効

  app:
    image: node:22-bullseye
    container_name: app
    ports:
      - "5465:5465"
    volumes:
      - ./src/node:/app
      - ./work:/work
    working_dir: /app
    environment:
      - DB_HOST=db
    command: npm start
    tty: true # 開発時のみ有効

  db:
    container_name: db
    image: postgres:17-alpine
    restart: always
    shm_size: 256mb
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 3
    volumes:
      - db-data:/var/lib/postgresql/data
      - ./work:/work
    working_dir: /work
    environment:
      POSTGRES_HOST_AUTH_METHOD: "${POSTGRES_HOST_AUTH_METHOD}"
      POSTGRES_USER: "${POSTGRES_USER}"
      POSTGRES_DB: "${POSTGRES_DB}"
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
    env_file:
      - .env

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    ports:
      - 8888:80
    volumes:
      - ./pgadmin:/var/lib/pgadmin
      - ./work:/work
    environment:
      PGADMIN_DEFAULT_EMAIL: "${PGADMIN_DEFAULT_EMAIL}"
      PGADMIN_DEFAULT_PASSWORD: "${PGADMIN_DEFAULT_PASSWORD}"
    depends_on:
      - db
    env_file:
      - .env
      
volumes:
  db-data: